#!/bin/bash
# while inotifywait -e modify -e close_write -r ../* ;do cd ../build/ && make -j4 && ./bin/runUnitTests --gtest_filter=*kd_search*;done
while inotifywait -e modify -e close_write -r ../* ;do cd ../build/ && make -j6 && make test -j4;done
