#!/bin/bash
# while inotifywait -e modify -e close_write -r ../* ;do cd ../build/ && make -j4 && ./bin/runUnitTests --gtest_filter=*;done
while inotifywait -e modify -e close_write -r ../* ;do cd ../build/ && make test -j4;done
